import 'package:hive/hive.dart';

import '../../domain/entities/settings_entity.dart';

/// Hive-persisted version of [SettingsEntity].
///
/// `typeId: 1` — `0` is already used by [UserLoginModel]; keep ids stable
/// and unique across the whole app when adding more `@HiveType` classes.
///
/// Like `UserLoginModel`, [SettingsModelAdapter] below is hand-written
/// rather than generated by `hive_generator`/`build_runner`, to keep this
/// project buildable without a codegen step.
class SettingsModel {
  final String languageCode;
  final bool hardwareAcceleration;
  final int defaultPlayerIndex; // PlayerBackend.index
  final int bufferSizeMs;
  final String? parentalPinHash;
  final bool incognito;

  const SettingsModel({
    required this.languageCode,
    required this.hardwareAcceleration,
    required this.defaultPlayerIndex,
    required this.bufferSizeMs,
    this.parentalPinHash,
    this.incognito = false,
  });

  factory SettingsModel.fromEntity(SettingsEntity entity) {
    return SettingsModel(
      languageCode: entity.language.code,
      hardwareAcceleration: entity.hardwareAcceleration,
      defaultPlayerIndex: entity.defaultPlayer.index,
      bufferSizeMs: entity.bufferSizeMs,
      parentalPinHash: entity.parentalPinHash,
      incognito: entity.incognito,
    );
  }

  SettingsEntity toEntity() {
    return SettingsEntity(
      language: AppLanguage.fromCode(languageCode),
      hardwareAcceleration: hardwareAcceleration,
      defaultPlayer: PlayerBackend.values[defaultPlayerIndex],
      bufferSizeMs: bufferSizeMs,
      parentalPinHash: parentalPinHash,
      incognito: incognito,
    );
  }
}

/// Hand-written Hive `TypeAdapter` (see class doc above for why).
class SettingsModelAdapter extends TypeAdapter<SettingsModel> {
  @override
  final int typeId = 1;

  @override
  SettingsModel read(BinaryReader reader) {
    final fieldCount = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < fieldCount; i++) reader.readByte(): reader.read(),
    };
    return SettingsModel(
      languageCode: fields[0] as String,
      hardwareAcceleration: fields[1] as bool,
      defaultPlayerIndex: fields[2] as int,
      bufferSizeMs: fields[3] as int,
      parentalPinHash: fields[4] as String?,
      // Field 5 was added after the first release — settings written before
      // that decode as `false` rather than throwing.
      incognito: (fields[5] as bool?) ?? false,
    );
  }

  @override
  void write(BinaryWriter writer, SettingsModel obj) {
    writer
      ..writeByte(6)
      ..writeByte(0)
      ..write(obj.languageCode)
      ..writeByte(1)
      ..write(obj.hardwareAcceleration)
      ..writeByte(2)
      ..write(obj.defaultPlayerIndex)
      ..writeByte(3)
      ..write(obj.bufferSizeMs)
      ..writeByte(4)
      ..write(obj.parentalPinHash)
      ..writeByte(5)
      ..write(obj.incognito);
  }
}
